theme: "jekyll-theme-cayman"
title: "Hawks Robotics Documentation"
description: "Onboarding guides, tutorials, references, and Javadocs for our repository."
include:
  - "_references"
plugins:
  - "jekyll-octicons"
